<?php
/** Simplified Chinese UI strings. */

defined( 'ABSPATH' ) || exit;

return [
	'nav_home'        => '首页',
	'nav_fleet'       => '我们的车队',
	'nav_places'      => '景点推荐',
	'nav_travel_info' => '旅行信息',
	'nav_music'       => '格鲁吉亚音乐',
	'nav_blog'        => '博客',
	'nav_terms'       => '条款',
	'nav_contact'     => '联系我们',
	'book_now'        => '立即预订',

	'hero_title'      => '以你的方式探索格鲁吉亚',
	'hero_subtitle'   => '高端四驱车队，专为高加索山路而备 — 含全险，机场免费送车',
	'hero_cta'        => '浏览车队',
	'hero_cta2'       => '查看目的地',

	'trust_cancel'    => '免费取消',
	'trust_fees'      => '无隐藏费用',
	'trust_delivery'  => '机场免费送车',
	'trust_support'   => 'WhatsApp 全天候客服',
	'trust_insurance' => '含保险',

	'fleet_title'     => '我们的车队',
	'fleet_subtitle'  => '真实车辆，真实照片 — 您预订哪辆，就开走哪辆',
	'seats'           => '座',
	'automatic'       => '自动挡',
	'manual'          => '手动挡',
	'gasoline'        => '汽油',
	'diesel'          => '柴油',
	'hybrid'          => '混动',
	'electric'        => '电动',
	'available'       => '可预订',
	'unavailable'     => '已预订',
	'from_per_day'    => '起/天',
	'per_day'         => '/天',
	'days'            => '天',
	'view_all'        => '查看全部',
	'view_details'    => '详情',
	'photos_soon'     => '照片即将上线',

	'booking_title'      => '预订这辆车',
	'pickup_date'        => '取车日期',
	'return_date'        => '还车日期',
	'total_price'        => '总价',
	'price_per_day'      => '每天价格',
	'total_days'         => '总天数',
	'your_name'          => '您的姓名',
	'book_whatsapp'      => '通过 WhatsApp 预订',
	'no_prepayment'      => '无需预付 — 取车时付款',
	'free_cancellation'  => '取车前 24 小时内可免费取消',
	'price_locked'       => '此价格为最终价格 — WhatsApp 仅作确认',
	'select_dates'       => '选择日期',
	'quote_error'        => '无法计算价格 — 请尝试其他日期',
	'booking_summary'    => '预订摘要',
	'send_request'       => '在 WhatsApp 发送请求',
	'whats_next_title'   => '接下来会怎样？',
	'whats_next_text'    => '我们将在 30 分钟内确认（09:00–22:00）。取车时付款。',

	'pricing_title'   => '季节性价格（美元/天）',
	'season'          => '季节',
	'days_label'      => '天',

	'specs_title'       => '车辆参数',
	'spec_year'         => '年份',
	'spec_seats'        => '座位数',
	'spec_transmission' => '变速箱',
	'spec_fuel'         => '燃料',
	'spec_color'        => '颜色',
	'spec_body'         => '车身类型',

	'terrain_title'   => '您可以去哪里',
	'terrain_text'    => '卡兹别克、古道里、卡赫季、斯瓦涅季 — 我们所有车辆均可行驶山路和碎石路。图舍季路线也欢迎咨询。',
	'included_title'  => '全部包含',
	'included_1'      => '全额保险',
	'included_2'      => '不限里程',
	'included_3'      => '冬季轮胎（应季）',
	'included_4'      => '免费第二驾驶员',
	'included_5'      => '机场免费送车',
	'included_6'      => '24/7 道路救援',

	'process_title'   => '预订流程',
	'process_1_t'     => '选择车辆和日期',
	'process_1_d'     => '按季节和租期即时显示准确价格',
	'process_2_t'     => '通过 WhatsApp 发送请求',
	'process_2_d'     => '含预订编号的现成消息 — 30 分钟内确认',
	'process_3_t'     => '出发上路',
	'process_3_d'     => '取车时付款。提车即刻开启您的冒险',

	'routes_title'       => '我们的车能带您去哪里',
	'route_1'            => '卡兹别克与古道里',
	'route_2'            => '卡赫季葡萄酒之路',
	'route_3'            => '斯瓦涅季',
	'route_4'            => '黑海海岸',
	'testimonials_title' => '客户评价',
	'faq_title'          => '常见问题',
	'cta_title'          => '准备好探索格鲁吉亚了吗？',
	'cta_subtitle'       => '选好车和日期 — 其余交给我们',
	'places_title'       => '景点推荐',
	'places_subtitle'    => '探索格鲁吉亚最美的目的地',
	'all_regions'        => '所有地区',
	'view_on_map'        => '在地图上查看',

	'footer_desc'     => '格鲁吉亚高端租车服务。舒适可靠地探索高加索之美。',
	'quick_links'     => '快捷链接',
	'contact_info'    => '联系方式',
	'follow_us'       => '关注我们',
	'rights'          => '版权所有。',

	'contact_title'    => '联系我们',
	'contact_subtitle' => '如有任何问题、定制方案或需要帮助，请联系我们',
	'contact_whatsapp' => '在 WhatsApp 上联系',
	'contact_phone'    => '致电我们',
	'contact_email'    => '发送邮件',
	'contact_hours'    => '营业时间',
	'contact_address'  => '地址',
];
