<?php
/** French UI strings. */

defined( 'ABSPATH' ) || exit;

return [
	'from' => 'à partir de',
	'nav_locations' => 'Villes',
	'nav_where_drive' => 'Où vous pouvez rouler',
	'nav_guides' => 'Guides',
	'nav_trust' => 'Confiance et conditions',
	'breadcrumb' => 'Fil d’Ariane',
	'price_on_request' => 'Prix sur demande',
	'nav_home'        => 'Accueil',
	'nav_fleet'       => 'Notre flotte',
	'nav_places'      => 'À visiter',
	'nav_travel_info' => 'Infos voyage',
	'nav_music'       => 'Musique géorgienne',
	'nav_blog'        => 'Blog',
	'nav_terms'       => 'Conditions',
	'nav_contact'     => 'Contact',
	'nav_about'       => 'À propos de Geolander',
	'book_now'        => 'Réserver',

	'hero_title'      => 'Location de 4×4 à Tbilissi, en Géorgie — la voiture que vous réservez est exactement celle que vous recevez',
	'hero_subtitle'   => 'Une flotte 4x4 premium pour les routes du Caucase — assurance complète incluse et livraison gratuite à l\'aéroport de Tbilissi',
	'hero_cta'        => 'Voir notre flotte',
	'hero_cta2'       => 'Voir les destinations',

	'trust_cancel'    => 'Conditions d’annulation claires',
	'trust_fees'      => 'Sans frais cachés',
	'trust_delivery'  => 'Livraison gratuite à l\'aéroport de Tbilissi',
	'trust_support'   => 'Assistance 24h/24 sur WhatsApp',
	'trust_insurance' => 'Assurance incluse',

	'fleet_title'     => 'Notre flotte',
	'fleet_subtitle'  => 'De vraies voitures, de vraies photos — vous recevez exactement la voiture que vous réservez',
	'seats'           => 'places',
	'automatic'       => 'Automatique',
	'manual'          => 'Manuelle',
	'gasoline'        => 'Essence',
	'diesel'          => 'Diesel',
	'hybrid'          => 'Hybride',
	'electric'        => 'Électrique',
	'available'       => 'Disponible',
	'unavailable'     => 'Réservée',
	'from_per_day'    => 'dès/jour',
	'per_day'         => '/jour',
	'days'            => 'jours',
	'view_all'        => 'Tout voir',
	'view_details'    => 'Détails',
	'photos_soon'     => 'Photos à venir',

	'booking_title'      => 'Réserver cette voiture',
	'pickup_date'        => 'Date de prise en charge',
	'return_date'        => 'Date de retour',
	'total_price'        => 'Prix total',
	'price_per_day'      => 'Prix par jour',
	'total_days'         => 'Nombre de jours',
	'your_name'          => 'Votre nom',
	'book_whatsapp'      => 'Réserver via WhatsApp',
	'booking_prepayment'  => 'Un prépaiement de 10 % confirme la réservation',
	'cancellation_refund' => '50 % du prépaiement est remboursable au moins 30 jours avant la prise en charge',
	'price_locked'       => 'Le total comprend la location et les frais de prise en charge/retour choisis ; WhatsApp confirme la disponibilité',
	'select_dates'       => 'Choisissez vos dates',
	'quote_error'        => 'Impossible de calculer le prix — essayez d\'autres dates',
	'booking_summary'    => 'Récapitulatif de réservation',
	'send_request'       => 'Envoyer la demande sur WhatsApp',
	'whats_next_title'   => 'Et ensuite ?',
	'whats_next_text'    => 'Confirmation sous 30 minutes (09h00–22h00). Un prépaiement de 10 % confirme la réservation.',

	'pricing_title'   => 'Tarifs saisonniers (USD/jour)',
	'season'          => 'Saison',
	'days_label'      => 'jours',

	'specs_title'       => 'Caractéristiques',
	'spec_year'         => 'Année',
	'spec_seats'        => 'Places',
	'spec_transmission' => 'Boîte',
	'spec_fuel'         => 'Carburant',
	'spec_color'        => 'Couleur',
	'spec_body'         => 'Carrosserie',

	'terrain_title'   => 'Où pouvez-vous aller',
	'terrain_text'    => 'Kazbegi, Goudaouri, Kakhétie, Svanétie — toutes nos voitures sont autorisées sur les routes de montagne et les pistes. Demandez-nous aussi pour la Touchétie.',
	'included_title'  => 'Inclus dans chaque location',
	'included_1'      => 'Assurance complète',
	'included_2'      => 'Kilométrage illimité',
	'included_3'      => 'Pneus hiver en saison',
	'included_4'      => 'Aucun dépôt de garantie',
	'included_5'      => 'Livraison gratuite à l\'aéroport de Tbilissi',
	'included_6'      => 'Assistance WhatsApp 24 h/24',

	'process_title'   => 'Comment ça marche',
	'process_1_t'     => 'Choisissez votre voiture et vos dates',
	'process_1_d'     => 'Votre prix exact s\'affiche instantanément — selon la saison et la durée',
	'process_2_t'     => 'Envoyez une demande via WhatsApp',
	'process_2_d'     => 'Un message prêt avec votre numéro de réservation — confirmation en 30 minutes',
	'process_3_t'     => 'Confirmez avec 10 %',
	'process_3_d'     => 'Versez 10 % pour confirmer. Payez le solde à la prise en charge',

	'routes_title'       => 'Où nos voitures vous emmènent',
	'route_1'            => 'Kazbegi et Goudaouri',
	'route_2'            => 'Route des vins de Kakhétie',
	'route_3'            => 'Svanétie',
	'route_4'            => 'Côte de la mer Noire',
	'testimonials_title' => 'Avis clients sur Google Maps',
	'faq_title'          => 'Questions fréquentes',
	'cta_title'          => 'Prêt à explorer la Géorgie ?',
	'cta_subtitle'       => 'Choisissez une voiture et vos dates — nous nous occupons du reste',
	'places_title'       => 'À visiter',
	'places_subtitle'    => 'Découvrez les plus belles destinations de Géorgie',
	'all_regions'        => 'Toutes les régions',
	'view_on_map'        => 'Voir sur la carte',
	'place_driving_title'  => 'Aller à %s en voiture',
	'place_drive_plan'     => 'Préparer le trajet',
	'place_driving_policy' => 'Vérifiez la météo, les fermetures officielles et l’état de la route avant le départ. Une autorisation de location ne permet jamais d’emprunter une route fermée ou dangereuse.',
	'place_route_guides'   => 'Lire les guides de conduite',
	'place_choose_car'     => 'Comparer les vrais 4x4 et AWD',

	'footer_desc'     => 'Service premium de location de voitures en Géorgie. Découvrez la beauté du Caucase avec confort et fiabilité.',
	'quick_links'     => 'Liens rapides',
	'contact_info'    => 'Coordonnées',
	'follow_us'       => 'Suivez-nous',
	'we_deliver'       => 'Livraison à',
	'rights'          => 'Tous droits réservés.',

	'contact_title'    => 'Agence de location à Mtatsminda, Tbilissi',
	'contact_subtitle' => 'Écrivez-nous pour toute question, offre personnalisée ou assistance',
	'contact_whatsapp' => 'Écrire sur WhatsApp',
	'contact_phone'    => 'Appeler',
	'contact_email'    => 'Envoyer un e-mail',
	'contact_hours'    => 'Horaires',
	'contact_address'  => 'Adresse',
	'contact_form_title'    => 'Envoyez-nous un message',
	'contact_form_name'     => 'Nom',
	'contact_form_email'    => 'E-mail',
	'contact_form_phone'    => 'Téléphone (facultatif)',
	'contact_form_message'  => 'Message',
	'contact_form_send'     => 'Continuer sur WhatsApp',
	'contact_form_sent'     => 'Merci — votre message a été envoyé.',
	'contact_form_error'    => 'Votre message n’a pas pu être envoyé. Réessayez ou contactez-nous sur WhatsApp.',
	'contact_google_rating' => 'Note de %s sur Google Maps',
	'contact_map_title'     => 'Bureau Geolander sur Google Maps',
	'office_location'       => 'Notre agence de location de 4x4 se trouve au cœur de Tbilissi — %1$s, %2$s.',

	// Positioning + fleet card CTA.
	'slogan'            => 'Venez pour les routes. Repartez avec les souvenirs.',
	'price_range_label' => 'Toutes les voitures',
	'price_range_sentence' => 'De %1$s à %2$s par jour',
	'ask_whatsapp'      => 'Écrire sur WhatsApp',
	'check_details'      => 'Voir les détails',

	// 404 page.
	'nf_code'          => '404',
	'nf_text'          => 'Page introuvable. Retour à',
	'nf_home'          => 'l’accueil',
	'nf_or'            => 'ou',
	'nf_fleet'         => 'découvrez notre flotte',
	'nf_agent_recovery'=> 'Liens de récupération pour agents',

	// Added 2026-09-07 — key parity with strings-en.php
	'your_email'         => 'Votre e-mail',
	'pickup_location'    => 'Lieu de prise en charge',
	'return_location'    => 'Lieu de restitution',
	'free'               => 'Gratuit',
	'location_tbilisi_office'  => 'Bureau de Tbilissi · Mtatsminda',
	'location_tbilisi_airport' => 'Aéroport de Tbilissi (TBS)',
	'location_kutaisi_airport' => 'Aéroport de Koutaïssi (KUT)',
	'location_batumi_airport'  => 'Aéroport de Batoumi (BUS)',
	'rental_price'       => 'Location du véhicule',
	'pickup_charge'      => 'Frais de prise en charge',
	'return_charge'      => 'Frais de restitution',
	'final_total'        => 'Total final affiché',
	'prepayment_amount'  => 'Acompte de confirmation de 10%',
	'balance_at_pickup'  => 'Solde à la prise en charge',
	'customer_details_error' => 'Saisissez votre nom et une adresse e-mail valide.',
	'receipt_sent'       => 'Nous vous avons envoyé le récapitulatif de votre demande par e-mail. Poursuivez sur WhatsApp pour que notre équipe confirme la disponibilité et l\'acompte de 10%.',
	'receipt_not_sent'   => 'Votre demande est enregistrée. Poursuivez sur WhatsApp ; notre équipe utilisera votre numéro de réservation et enverra la confirmation manuellement.',
	'spec_drivetrain'    => 'Transmission',
	'spec_fuel_economy'  => 'Consommation',
	'rental_facts_title'              => 'Des conditions de location claires pour cette voiture précise',
	'rental_exact_car'                => 'Garantie du véhicule',
	'rental_exact_car_value'          => 'La voiture exacte montrée et réservée — jamais « ou similaire »',
	'rental_winter'                   => 'Pneus hiver',
	'rental_winter_value'             => 'Montés en hiver et inclus sans supplément',
	'rental_insurance'                => 'Assurance incluse',
	'rental_insurance_value'          => 'Assurance tous risques, y compris les accidents sans tiers',
	'rental_excess'                   => 'Franchise',
	'rental_excess_value'             => 'Aucune',
	'rental_coverage'                 => 'Jantes et pare-brise',
	'rental_coverage_value'           => 'Couverts par l\'assurance',
	'rental_not_covered'              => 'Non couvert',
	'rental_not_covered_value'        => 'Les pneus',
	'rental_liability'                => 'Responsabilité civile',
	'rental_liability_value'          => 'Couverte jusqu\'à 30,000 GEL',
	'rental_deposit'                  => 'Dépôt de garantie',
	'rental_deposit_value'            => 'Aucun — ni espèces, ni débit de carte, ni préautorisation',
	'rental_mileage'                  => 'Kilométrage',
	'rental_mileage_value'            => 'Illimité en Géorgie',
	'rental_delivery'                 => 'Prise en charge / restitution à l\'aéroport',
	'rental_delivery_value'           => 'Tbilissi est gratuit. Koutaïssi : %1$s par trajet ; Batoumi : %2$s par trajet.',
	'rental_insurance_exclusions'     => 'L\'assurance est annulée en cas de circulation à contresens, de franchissement d\'un feu rouge, d\'excès de vitesse ou de défaut d\'information de Geolander sur le lieu de l\'incident.',
	'city_seo_title'       => 'Location de voiture à %s, Géorgie (pays) — sans caution, assurance incluse',
	'city_seo_description' => 'Louez une 4x4 ou AWD précise livrée à %s, en Géorgie (pays). Sans caution, assurance tous risques incluse, photos réelles de la voiture que vous recevrez, assistance WhatsApp 24/7.',
	'longterm_table_title' => 'Tarifs longue durée selon la durée de location (USD par jour)',
	'longterm_vehicle'     => 'Véhicule',
	'longterm_season'      => 'Saison',
	'longterm_tier_short'  => '1–2 jours',
	'longterm_tier_19_30'  => '19–30 jours',
	'longterm_tier_31'     => '31+ jours',
	'longterm_saving'      => 'Économie à 31+ jours par rapport à une location courte',
	'longterm_note'        => 'Les tarifs sont lus en direct dans la table des prix saisonniers de chaque voiture. Une location à cheval sur deux saisons est facturée jour par jour au tarif de chaque saison.',
	'longterm_cta'         => 'Demander un devis mensuel sur WhatsApp',
	'longterm_unpriced'    => 'Prix sur demande',
	'nav_long_term'        => 'Location longue durée',
	'home_seo_title'       => 'Location de 4x4 en Géorgie (pays) — Tbilissi',
	// Evidence-led rental planning; business facts come from live settings.
	'arrival_title' => 'Comparer les frais de livraison aux aéroports',
	'arrival_intro' => 'Avant de choisir Tbilissi, Koutaïssi ou Batoumi, comparez les économies sur les vols aux frais de livraison du véhicule. Ce tableau utilise les tarifs actuels du formulaire de réservation.',
	'arrival_caption' => 'Livraison du véhicule en USD — location en supplément',
	'arrival_airport' => 'Aéroport',
	'arrival_one_way' => 'Prise en charge OU retour',
	'arrival_round_trip' => 'Prise en charge ET retour',
	'arrival_included' => 'Inclus',
	'arrival_math' => 'Pour une même location, comparez les économies de billets de tout le groupe aux deux frais de livraison. Si les aéroports diffèrent, additionnez les frais de chaque trajet.',
	'arrival_limits' => 'Ce tableau ne compare pas le coût total du voyage. Vols, carburant, temps de trajet et autres dépenses sont exclus. Saisissez vos dates sur une fiche véhicule ; faites confirmer la disponibilité et tous les frais avant de payer.',
	'arrival_checklist_title' => 'Questions à poser à tout loueur',
	'arrival_check_car' => 'Quel véhicule exact recevrai-je ? Demandez la plaque, des photos récentes, le type de transmission aux roues et des informations datées sur les pneus.',
	'arrival_check_cover' => 'Que couvre l’assurance, quelles sont les exclusions, la franchise et la limite de responsabilité civile ? Vérifiez séparément pneus, jantes et vitres.',
	'arrival_check_cost' => 'Quel est le prix total écrit, avec prise en charge, retour, taxes et options ? Distinguez l’acompte de réservation du dépôt de garantie.',
	'arrival_check_route' => 'Mon itinéraire précis est-il autorisé pour ces dates et ce véhicule ? Quel est l’effet de la météo, des fermetures et des routes endommagées ?',
	'arrival_check_confirm' => 'Qu’est-ce qui confirme ma réservation, comment recevrai-je la confirmation et quel remboursement en cas d’annulation ? Obtenez le contrat avant de payer.',
	'arrival_quote' => 'Choisir un véhicule et calculer vos dates',
	'evidence_title' => 'Informations datées sur le véhicule',
	'evidence_checked' => 'Vérifié le :',
	'evidence_odometer' => 'Kilométrage lors de la vérification',
	'evidence_service' => 'Date d’entretien documentée',
	'evidence_tyres' => 'Observation des pneus',
	'evidence_luggage' => 'Observation du coffre',
	'evidence_note' => 'Ces observations du propriétaire correspondent à la date indiquée ; elles ne constituent ni un contrôle actuel ni une garantie de bon état. Demandez des photos actualisées avant de réserver.',
];
