<?php
/** Simplified Chinese UI strings. */

defined( 'ABSPATH' ) || exit;

return [
	'from' => '起',
	'nav_locations' => '城市',
	'nav_where_drive' => '可行驶路线',
	'nav_guides' => '指南',
	'nav_trust' => '信任与条款',
	'breadcrumb' => '导航路径',
	'price_on_request' => '价格面议',
	'nav_home'        => '首页',
	'nav_fleet'       => '我们的车队',
	'nav_places'      => '景点推荐',
	'nav_travel_info' => '旅行信息',
	'nav_music'       => '格鲁吉亚音乐',
	'nav_blog'        => '博客',
	'nav_terms'       => '条款',
	'nav_contact'     => '联系我们',
	'nav_about'       => '关于 Geolander',
	'book_now'        => '立即预订',

	'hero_title'      => '第比利斯 4×4 租车（格鲁吉亚）— 您预订的就是您拿到的那辆车',
	'hero_subtitle'   => '高端四驱车队，专为高加索山路而备 — 含全险，第比利斯机场免费送车',
	'hero_cta'        => '浏览车队',
	'hero_cta2'       => '查看目的地',

	'trust_cancel'    => '明确的取消条款',
	'trust_fees'      => '无隐藏费用',
	'trust_delivery'  => '第比利斯机场免费送车',
	'trust_support'   => 'WhatsApp 全天候客服',
	'trust_insurance' => '含保险',

	'fleet_title'     => '我们的车队',
	'fleet_subtitle'  => '真实车辆，真实照片 — 您预订哪辆，就开走哪辆',
	'seats'           => '座',
	'automatic'       => '自动挡',
	'manual'          => '手动挡',
	'gasoline'        => '汽油',
	'diesel'          => '柴油',
	'hybrid'          => '混动',
	'electric'        => '电动',
	'available'       => '可预订',
	'unavailable'     => '已预订',
	'from_per_day'    => '起/天',
	'per_day'         => '/天',
	'days'            => '天',
	'view_all'        => '查看全部',
	'view_details'    => '详情',
	'photos_soon'     => '照片即将上线',

	'booking_title'      => '预订这辆车',
	'pickup_date'        => '取车日期',
	'return_date'        => '还车日期',
	'total_price'        => '总价',
	'price_per_day'      => '每天价格',
	'total_days'         => '总天数',
	'your_name'          => '您的姓名',
	'book_whatsapp'      => '通过 WhatsApp 预订',
	'booking_prepayment'  => '支付10%预付款即可确认预订',
	'cancellation_refund' => '如在取车前30天或更早取消，可退还预付款的50%',
	'price_locked'       => '总价包含租金及所选取还车费用；车辆可用性通过 WhatsApp 确认',
	'select_dates'       => '选择日期',
	'quote_error'        => '无法计算价格 — 请尝试其他日期',
	'booking_summary'    => '预订摘要',
	'send_request'       => '在 WhatsApp 发送请求',
	'whats_next_title'   => '接下来会怎样？',
	'whats_next_text'    => '我们将在30分钟内确认（09:00–22:00）。支付10%预付款后预订生效。',

	'pricing_title'   => '季节性价格（美元/天）',
	'season'          => '季节',
	'days_label'      => '天',

	'specs_title'       => '车辆参数',
	'spec_year'         => '年份',
	'spec_seats'        => '座位数',
	'spec_transmission' => '变速箱',
	'spec_fuel'         => '燃料',
	'spec_color'        => '颜色',
	'spec_body'         => '车身类型',

	'terrain_title'   => '您可以去哪里',
	'terrain_text'    => '卡兹别克、古道里、卡赫季、斯瓦涅季 — 我们所有车辆均可行驶山路和碎石路。图舍季路线也欢迎咨询。',
	'included_title'  => '每次租车均包含',
	'included_1'      => '全额保险',
	'included_2'      => '不限里程',
	'included_3'      => '冬季轮胎（应季）',
	'included_4'      => '无需押金',
	'included_5'      => '第比利斯机场免费送车',
	'included_6'      => '全天候 WhatsApp 支持',

	'process_title'   => '预订流程',
	'process_1_t'     => '选择车辆和日期',
	'process_1_d'     => '按季节和租期即时显示准确价格',
	'process_2_t'     => '通过 WhatsApp 发送请求',
	'process_2_d'     => '含预订编号的现成消息 — 30 分钟内确认',
	'process_3_t'     => '支付10%确认预订',
	'process_3_d'     => '支付10%确认预订，余款取车时支付',

	'routes_title'       => '我们的车能带您去哪里',
	'route_1'            => '卡兹别克与古道里',
	'route_2'            => '卡赫季葡萄酒之路',
	'route_3'            => '斯瓦涅季',
	'route_4'            => '黑海海岸',
	'testimonials_title' => 'Google 地图上的客户评价',
	'faq_title'          => '常见问题',
	'cta_title'          => '准备好探索格鲁吉亚了吗？',
	'cta_subtitle'       => '选好车和日期 — 其余交给我们',
	'places_title'       => '景点推荐',
	'places_subtitle'    => '探索格鲁吉亚最美的目的地',
	'all_regions'        => '所有地区',
	'view_on_map'        => '在地图上查看',
	'place_driving_title'  => '自驾前往%s',
	'place_drive_plan'     => '规划驾驶路线',
	'place_driving_policy' => '出发前请检查天气、官方封路信息和道路损坏情况。租车许可不能凌驾于封闭或不安全的道路状况之上。',
	'place_route_guides'   => '阅读驾驶指南',
	'place_choose_car'     => '比较真实的 4x4 和 AWD 车辆',

	'footer_desc'     => '格鲁吉亚高端租车服务。舒适可靠地探索高加索之美。',
	'quick_links'     => '快捷链接',
	'contact_info'    => '联系方式',
	'follow_us'       => '关注我们',
	'we_deliver'       => '送车城市',
	'rights'          => '版权所有。',

	'contact_title'    => '第比利斯姆塔茨明达汽车租赁办公室',
	'contact_subtitle' => '如有任何问题、定制方案或需要帮助，请联系我们',
	'contact_whatsapp' => '在 WhatsApp 上联系',
	'contact_phone'    => '致电我们',
	'contact_email'    => '发送邮件',
	'contact_hours'    => '营业时间',
	'contact_address'  => '地址',
	'contact_form_title'    => '给我们留言',
	'contact_form_name'     => '姓名',
	'contact_form_email'    => '电子邮箱',
	'contact_form_phone'    => '电话（选填）',
	'contact_form_message'  => '留言',
	'contact_form_send'     => '在 WhatsApp 中继续',
	'contact_form_sent'     => '谢谢 — 您的留言已发送。',
	'contact_form_error'    => '无法发送您的留言。请重试或通过 WhatsApp 联系我们。',
	'contact_google_rating' => 'Google 地图评分 %s',
	'contact_map_title'     => 'Google 地图上的 Geolander 办公室',
	'office_location'       => '我们的 4x4 租车办公室位于第比利斯市中心 — %1$s，%2$s。',

	// Positioning + fleet card CTA.
	'slogan'            => '为道路而来，带回忆而归。',
	'price_range_label' => '所有车辆',
	'price_range_sentence' => '每天 %1$s 至 %2$s',
	'ask_whatsapp'      => '通过 WhatsApp 咨询',
	'check_details'      => '查看详情',

	// 404 page.
	'nf_code'          => '404',
	'nf_text'          => '页面未找到。返回',
	'nf_home'          => '首页',
	'nf_or'            => '或',
	'nf_fleet'         => '浏览我们的车队',
	'nf_agent_recovery'=> '智能代理恢复链接',

	// Added 2026-09-07 — key parity with strings-en.php
	'your_email'         => '您的邮箱',
	'pickup_location'    => '取车地点',
	'return_location'    => '还车地点',
	'free'               => '免费',
	'location_tbilisi_office'  => '第比利斯办公室 · 姆塔茨明达',
	'location_tbilisi_airport' => '第比利斯机场 (TBS)',
	'location_kutaisi_airport' => '库塔伊西机场 (KUT)',
	'location_batumi_airport'  => '巴统机场 (BUS)',
	'rental_price'       => '车辆租金',
	'pickup_charge'      => '取车费用',
	'return_charge'      => '还车费用',
	'final_total'        => '最终总价',
	'prepayment_amount'  => '10% 确认预付款',
	'balance_at_pickup'  => '取车时支付的余款',
	'customer_details_error' => '请输入您的姓名和有效的邮箱地址。',
	'receipt_sent'       => '我们已将您的申请摘要发送到您的邮箱。请继续前往 WhatsApp，我们的团队将确认车辆是否可租以及 10% 预付款。',
	'receipt_not_sent'   => '您的申请已保存。请继续前往 WhatsApp；我们的团队可凭您的预订编号手动发送确认信息。',
	'spec_drivetrain'    => '驱动方式',
	'spec_fuel_economy'  => '油耗',
	'rental_facts_title'              => '这辆车的明确租赁条款',
	'rental_exact_car'                => '车辆保证',
	'rental_exact_car_value'          => '您看到并预订的就是您拿到的那辆车 — 绝不会是“或同类车型”',
	'rental_winter'                   => '冬季轮胎',
	'rental_winter_value'             => '冬季安装，免费提供',
	'rental_insurance'                => '含保险',
	'rental_insurance_value'          => '全额保险，包含单车事故',
	'rental_excess'                   => '免赔额',
	'rental_excess_value'             => '无',
	'rental_coverage'                 => '轮毂与挡风玻璃',
	'rental_coverage_value'           => '保险已覆盖',
	'rental_not_covered'              => '不在保障范围内',
	'rental_not_covered_value'        => '轮胎',
	'rental_liability'                => '第三方责任',
	'rental_liability_value'          => '最高赔付 30,000 GEL',
	'rental_deposit'                  => '押金',
	'rental_deposit_value'            => '无 — 不收现金、不刷卡扣款，也不做信用卡预授权',
	'rental_mileage'                  => '里程',
	'rental_mileage_value'            => '格鲁吉亚境内不限里程',
	'rental_delivery'                 => '机场取车 / 还车',
	'rental_delivery_value'           => '第比利斯免费。库塔伊西单程 %1$s；巴统单程 %2$s。',
	'rental_insurance_exclusions'     => '如逆向行驶、闯红灯、超速，或未向 Geolander 告知事故地点，保险将失效。',
	'city_seo_title'       => '%s 租车 — 格鲁吉亚（国家），免押金、全额保险',
	'city_seo_description' => '在格鲁吉亚 %s 租用指定的 4x4 或 AWD 车型并送车上门。无需押金，含全额保险，提供您所租车辆的真实照片，24/7 WhatsApp 支持。',
	'longterm_table_title' => '按租期划分的长租日租金（美元/天）',
	'longterm_vehicle'     => '车辆',
	'longterm_season'      => '季节',
	'longterm_tier_short'  => '1–2 天',
	'longterm_tier_19_30'  => '19–30 天',
	'longterm_tier_31'     => '31+ 天',
	'longterm_saving'      => '租期 31+ 天相比短租的节省',
	'longterm_note'        => '价格实时读取自每辆车的季节价格表。若租期跨越两个季节，则按天分别适用各季节的价格计算。',
	'longterm_cta'         => '在 WhatsApp 上索取月租报价',
	'longterm_unpriced'    => '价格面议',
	'nav_long_term'        => '长租',
	'home_seo_title'       => '格鲁吉亚（国家）4x4 租车 — 第比利斯',
	// Evidence-led rental planning; business facts come from live settings.
	'arrival_title' => '比较机场租车交付费用',
	'arrival_intro' => '选择第比利斯、库塔伊西或巴统机场前，请比较机票节省金额与车辆交付费用。本表采用与预订表单相同的当前收费。',
	'arrival_caption' => '车辆交付费用（美元）—租金另计',
	'arrival_airport' => '机场',
	'arrival_one_way' => '取车或还车',
	'arrival_round_trip' => '取车及还车',
	'arrival_included' => '已包含',
	'arrival_math' => '对于相同的租车安排，请将整个同行团队节省的机票费用与双程交付费比较。若取还车机场不同，请将两个地点各自的单程费用相加。',
	'arrival_limits' => '这不是完整的旅行费用比较，不包含机票、燃油、行程时间或其他费用。在车辆页面输入日期获取租金报价；付款前请向我们确认车辆是否可用及所有适用费用。',
	'arrival_checklist_title' => '向任何租车公司询问的问题',
	'arrival_check_car' => '我会拿到哪一辆具体车辆？请索取车牌号、近期照片、驱动类型及注明日期的轮胎信息。',
	'arrival_check_cover' => '保险涵盖什么，有哪些除外责任、免赔额及第三者责任限额？请单独确认轮胎、轮毂和玻璃。',
	'arrival_check_cost' => '包含取车、还车、税费及选配项目的书面总价是多少？请区分预订预付款与保证金。',
	'arrival_check_route' => '我的具体路线是否允许在这些日期使用这辆车行驶？天气、道路封闭及路面损坏如何影响许可？',
	'arrival_check_confirm' => '什么情况下预订才算确认，如何收到确认，取消时能退多少？付款前请取得协议。',
	'arrival_quote' => '选择车辆并计算所选日期的费用',
	'evidence_title' => '注明日期的车辆信息',
	'evidence_checked' => '核查日期：',
	'evidence_odometer' => '核查时里程表读数',
	'evidence_service' => '有记录的保养日期',
	'evidence_tyres' => '轮胎观察记录',
	'evidence_luggage' => '行李空间观察记录',
	'evidence_note' => '这些是车主在所示日期记录的信息，并非实时检查或车辆适驶保证。预订前请索取更新的照片。',
];
