<?php
/** English UI strings (fallback catalog / x-default). */

defined( 'ABSPATH' ) || exit;

return [
	'from' => 'from',
	'nav_locations' => 'Locations',
	'nav_where_drive' => 'Where you can drive',
	'nav_guides' => 'Guides',
	'nav_trust' => 'Trust & policies',
	'breadcrumb' => 'Breadcrumb',
	'price_on_request' => 'Price on request',
	'nav_home'        => 'Home',
	'nav_fleet'       => 'Our Fleet',
	'nav_places'      => 'Places to Visit',
	'nav_travel_info' => 'Travel Info',
	'nav_music'       => 'Georgian Music',
	'nav_blog'        => 'Blog',
	'nav_terms'       => 'Terms',
	'nav_contact'     => 'Contact',
	'book_now'        => 'Book Now',

	'hero_title'      => 'Explore Georgia Your Way',
	'hero_subtitle'   => 'Premium 4x4 car rental in Tbilisi, built for Caucasus mountain roads — full insurance included and free Tbilisi Airport delivery',
	'hero_cta'        => 'Browse Our Fleet',
	'hero_cta2'       => 'View Destinations',

	'trust_cancel'    => 'Clear cancellation terms',
	'trust_fees'      => 'No hidden fees',
	'trust_delivery'  => 'Free Tbilisi Airport delivery',
	'trust_support'   => '24/7 WhatsApp support',
	'trust_insurance' => 'Insurance included',

	'fleet_title'     => 'Our Fleet',
	'fleet_subtitle'  => 'Real cars, real photos — the exact car you book is the one you get',
	'seats'           => 'seats',
	'automatic'       => 'Automatic',
	'manual'          => 'Manual',
	'gasoline'        => 'Gasoline',
	'diesel'          => 'Diesel',
	'hybrid'          => 'Hybrid',
	'electric'        => 'Electric',
	'available'       => 'Available',
	'unavailable'     => 'Booked',
	'from_per_day'    => 'from/day',
	'per_day'         => '/day',
	'days'            => 'days',
	'view_all'        => 'View all',
	'view_details'    => 'Details',
	'photos_soon'     => 'Photos coming soon',

	'booking_title'      => 'Book this car',
	'pickup_date'        => 'Pickup date',
	'return_date'        => 'Return date',
	'total_price'        => 'Total price',
	'price_per_day'      => 'Price per day',
	'total_days'         => 'Total days',
	'your_name'          => 'Your name',
	'your_email'         => 'Your email',
	'pickup_location'    => 'Pickup location',
	'return_location'    => 'Return location',
	'free'               => 'Free',
	'location_tbilisi_office'  => 'Tbilisi office · Mtatsminda',
	'location_tbilisi_airport' => 'Tbilisi Airport (TBS)',
	'location_kutaisi_airport' => 'Kutaisi Airport (KUT)',
	'location_batumi_airport'  => 'Batumi Airport (BUS)',
	'rental_price'       => 'Vehicle rental',
	'pickup_charge'      => 'Pickup charge',
	'return_charge'      => 'Return charge',
	'final_total'        => 'Final total shown',
	'prepayment_amount'  => '10% confirmation prepayment',
	'balance_at_pickup'  => 'Balance at pickup',
	'book_whatsapp'      => 'Book via WhatsApp',
	'booking_prepayment'  => '10% prepayment confirms the booking',
	'cancellation_refund' => '50% of the prepayment is refundable 30+ days before pickup',
	'price_locked'       => 'The total includes the rental and selected pickup/return charges; WhatsApp confirms availability',
	'select_dates'       => 'Select dates',
	'quote_error'        => 'Could not price these dates — try different ones',
	'booking_summary'    => 'Booking summary',
	'send_request'       => 'Send request on WhatsApp',
	'whats_next_title'   => 'What happens next?',
	'whats_next_text'    => 'We confirm within 30 minutes (09:00–22:00). A 10% prepayment confirms the booking.',
	'customer_details_error' => 'Enter your name and a valid email address.',
	'receipt_sent'            => 'We emailed your request summary. Continue to WhatsApp so our team can confirm availability and the 10% prepayment.',
	'receipt_not_sent'        => 'Your request is saved. Continue to WhatsApp; our team can use your booking reference and send the generated confirmation manually.',

	'pricing_title'   => 'Seasonal pricing (USD/day)',
	'season'          => 'Season',
	'days_label'      => 'days',

	'specs_title'       => 'Specifications',
	'spec_year'         => 'Year',
	'spec_seats'        => 'Seats',
	'spec_transmission' => 'Transmission',
	'spec_drivetrain'   => 'Drive system',
	'spec_fuel'         => 'Fuel',
	'spec_fuel_economy' => 'Fuel economy',
	'spec_color'        => 'Color',
	'spec_body'         => 'Body type',

	'terrain_title'   => 'Where you can go',
	'terrain_text'    => 'Kazbegi, Gudauri, Kakheti, Svaneti — all our cars are permitted on mountain and gravel roads. Ask us about Tusheti too.',
	'included_title'  => 'Everything included',
	'included_1'      => 'Full insurance',
	'included_2'      => 'Unlimited mileage',
	'included_3'      => 'Winter tires in season',
	'included_4'      => 'Free second driver',
	'included_5'      => 'Free Tbilisi Airport delivery',
	'included_6'      => '24/7 roadside assistance',

	'rental_facts_title'              => 'Clear rental terms for this exact car',
	'rental_exact_car'                => 'Vehicle guarantee',
	'rental_exact_car_value'          => 'The exact car shown and booked — never “or similar”',
	'rental_winter'                   => 'Winter tyres',
	'rental_winter_value'             => 'Installed in winter and included free of charge',
	'rental_insurance'                => 'Insurance included',
	'rental_insurance_value'          => 'Full insurance, including single-vehicle accidents',
	'rental_excess'                   => 'Deductible / excess',
	'rental_excess_value'             => 'None',
	'rental_coverage'                 => 'Wheels and windshield',
	'rental_coverage_value'           => 'Covered by insurance',
	'rental_not_covered'              => 'Not covered',
	'rental_not_covered_value'        => 'Tyres',
	'rental_liability'                => 'Third-party liability',
	'rental_liability_value'          => 'Covered up to 30,000 GEL',
	'rental_deposit'                  => 'Security deposit',
	'rental_deposit_value'            => 'None — no cash, card charge, or preauthorization hold',
	'rental_mileage'                  => 'Mileage',
	'rental_mileage_value'            => 'Unlimited within Georgia',
	'rental_delivery'                 => 'Airport pickup / return',
	'rental_delivery_value'           => 'Tbilisi is free. Kutaisi is %1$s each way; Batumi is %2$s each way.',
	'rental_insurance_exclusions'     => 'Insurance is void for wrong-lane driving, running a red light, speeding, or failing to inform Geolander of the incident location.',

	'process_title'   => 'How it works',
	'process_1_t'     => 'Choose your car and dates',
	'process_1_d'     => 'Your exact price appears instantly — by season and rental length',
	'process_2_t'     => 'Send a request via WhatsApp',
	'process_2_d'     => 'A ready message with your booking number — we confirm within 30 minutes',
	'process_3_t'     => 'Confirm with 10%',
	'process_3_d'     => 'Pay 10% to confirm. Pay the remaining balance at pickup',

	'routes_title'       => 'Where our cars take you',
	'route_1'            => 'Kazbegi & Gudauri',
	'route_2'            => 'Kakheti Wine Route',
	'route_3'            => 'Svaneti',
	'route_4'            => 'Black Sea Coast',
	'testimonials_title' => 'What our customers say',
	'faq_title'          => 'Frequently asked questions',
	'cta_title'          => 'Ready to explore Georgia?',
	'cta_subtitle'       => 'Pick a car, pick your dates — we handle the rest',
	'places_title'       => 'Places to Visit',
	'places_subtitle'    => 'Discover the most beautiful destinations in Georgia',
	'all_regions'        => 'All regions',
	'view_on_map'        => 'View on map',
	'place_driving_title'  => 'Driving to %s',
	'place_drive_plan'     => 'Plan the drive',
	'place_driving_policy' => 'Check weather, official closures, and road damage before departure. Rental permission never overrides a closed or unsafe road.',
	'place_route_guides'   => 'Read driving guides',
	'place_choose_car'     => 'Compare exact 4x4 and AWD cars',

	'footer_desc'     => 'Premium car rental service in Georgia. Explore the beauty of the Caucasus with comfort and reliability.',
	'quick_links'     => 'Quick links',
	'contact_info'    => 'Contact info',
	'follow_us'       => 'Follow us',
	'we_deliver'       => 'We deliver to',
	'rights'          => 'All rights reserved.',

	'contact_title'    => 'Car rental office in Mtatsminda, Tbilisi',
	'contact_subtitle' => 'Write to us with questions, custom offers, or for any help',
	'contact_whatsapp' => 'Message us on WhatsApp',
	'contact_phone'    => 'Call us',
	'contact_email'    => 'Email us',
	'contact_hours'    => 'Business hours',
	'contact_address'  => 'Address',
	'contact_form_title'    => 'Send us a message',
	'contact_form_name'     => 'Name',
	'contact_form_email'    => 'Email',
	'contact_form_phone'    => 'Phone (optional)',
	'contact_form_message'  => 'Message',
	'contact_form_send'     => 'Continue on WhatsApp',
	'contact_form_sent'     => 'Thank you — your message has been sent.',
	'contact_form_error'    => 'We could not send your message. Try again or contact us on WhatsApp.',
	'contact_google_rating' => '%s rating on Google Maps',
	'contact_map_title'     => 'Geolander office on Google Maps',
	'office_location'       => 'Our 4x4 rental office is in the heart of Tbilisi — %1$s, %2$s.',

	// Positioning + fleet card CTA.
	'slogan'            => 'Come for the roads. Leave with the memories.',
	'price_range_label' => 'All cars',
	'ask_whatsapp'      => 'Ask on WhatsApp',
	'check_details'      => 'Check details',

	// 404 page.
	'nf_code'          => '404',
	'nf_text'          => 'Page not found. Go back',
	'nf_home'          => 'home',
	'nf_or'            => 'or',
	'nf_fleet'         => 'browse our fleet',
];
