<?php
/** Arabic UI strings (RTL). */

defined( 'ABSPATH' ) || exit;

return [
	'from' => 'من',
	'nav_locations' => 'المدن',
	'nav_where_drive' => 'أين يمكنك القيادة',
	'nav_guides' => 'أدلة',
	'nav_trust' => 'الثقة والشروط',
	'breadcrumb' => 'مسار التنقل',
	'price_on_request' => 'السعر عند الطلب',
	'nav_home'        => 'الرئيسية',
	'nav_fleet'       => 'أسطولنا',
	'nav_places'      => 'أماكن للزيارة',
	'nav_travel_info' => 'معلومات السفر',
	'nav_music'       => 'الموسيقى الجورجية',
	'nav_blog'        => 'المدونة',
	'nav_terms'       => 'الشروط',
	'nav_contact'     => 'اتصل بنا',
	'book_now'        => 'احجز الآن',

	'hero_title'      => 'اكتشف جورجيا على طريقتك',
	'hero_subtitle'   => 'أسطول دفع رباعي فاخر لطرق جبال القوقاز — تأمين شامل وتوصيل مجاني إلى مطار تبليسي',
	'hero_cta'        => 'تصفح أسطولنا',
	'hero_cta2'       => 'عرض الوجهات',

	'trust_cancel'    => 'شروط إلغاء واضحة',
	'trust_fees'      => 'بدون رسوم خفية',
	'trust_delivery'  => 'توصيل مجاني إلى مطار تبليسي',
	'trust_support'   => 'دعم واتساب على مدار الساعة',
	'trust_insurance' => 'التأمين مشمول',

	'fleet_title'     => 'أسطولنا',
	'fleet_subtitle'  => 'سيارات حقيقية وصور حقيقية — السيارة التي تحجزها هي التي تستلمها',
	'seats'           => 'مقاعد',
	'automatic'       => 'أوتوماتيك',
	'manual'          => 'يدوي',
	'gasoline'        => 'بنزين',
	'diesel'          => 'ديزل',
	'hybrid'          => 'هجين',
	'electric'        => 'كهربائي',
	'available'       => 'متاحة',
	'unavailable'     => 'محجوزة',
	'from_per_day'    => 'من/يوم',
	'per_day'         => '/يوم',
	'days'            => 'أيام',
	'view_all'        => 'عرض الكل',
	'view_details'    => 'التفاصيل',
	'photos_soon'     => 'الصور قريباً',

	'booking_title'      => 'احجز هذه السيارة',
	'pickup_date'        => 'تاريخ الاستلام',
	'return_date'        => 'تاريخ الإرجاع',
	'total_price'        => 'السعر الإجمالي',
	'price_per_day'      => 'السعر لليوم',
	'total_days'         => 'إجمالي الأيام',
	'your_name'          => 'اسمك',
	'book_whatsapp'      => 'احجز عبر واتساب',
	'booking_prepayment'  => 'دفعة مسبقة 10٪ تؤكد الحجز',
	'cancellation_refund' => 'يُسترد 50٪ من الدفعة المسبقة عند الإلغاء قبل الاستلام بـ30 يومًا أو أكثر',
	'price_locked'       => 'يشمل الإجمالي الإيجار ورسوم الاستلام والإرجاع المختارة؛ نؤكد التوفر عبر واتساب',
	'select_dates'       => 'اختر التواريخ',
	'quote_error'        => 'تعذر حساب السعر — جرّب تواريخ أخرى',
	'booking_summary'    => 'ملخص الحجز',
	'send_request'       => 'أرسل الطلب عبر واتساب',
	'whats_next_title'   => 'ماذا بعد؟',
	'whats_next_text'    => 'نؤكد خلال 30 دقيقة (09:00–22:00). يتطلب تأكيد الحجز دفعة مسبقة بنسبة 10٪.',

	'pricing_title'   => 'الأسعار الموسمية (دولار/يوم)',
	'season'          => 'الموسم',
	'days_label'      => 'أيام',

	'specs_title'       => 'المواصفات',
	'spec_year'         => 'السنة',
	'spec_seats'        => 'المقاعد',
	'spec_transmission' => 'ناقل الحركة',
	'spec_fuel'         => 'الوقود',
	'spec_color'        => 'اللون',
	'spec_body'         => 'نوع الهيكل',

	'terrain_title'   => 'إلى أين يمكنك الذهاب',
	'terrain_text'    => 'كازبيجي، جوداوري، كاخيتي، سفانيتي — جميع سياراتنا مسموح لها بالطرق الجبلية وغير المعبدة. اسألنا عن توشيتي أيضاً.',
	'included_title'  => 'كل شيء مشمول',
	'included_1'      => 'تأمين شامل',
	'included_2'      => 'كيلومترات غير محدودة',
	'included_3'      => 'إطارات شتوية في موسمها',
	'included_4'      => 'سائق ثانٍ مجاناً',
	'included_5'      => 'توصيل مجاني إلى مطار تبليسي',
	'included_6'      => 'مساعدة على الطريق 24/7',

	'process_title'   => 'كيف يعمل',
	'process_1_t'     => 'اختر سيارتك وتواريخك',
	'process_1_d'     => 'يظهر سعرك الدقيق فوراً — حسب الموسم ومدة الإيجار',
	'process_2_t'     => 'أرسل طلباً عبر واتساب',
	'process_2_d'     => 'رسالة جاهزة برقم حجزك — نؤكد خلال 30 دقيقة',
	'process_3_t'     => 'أكد الحجز بدفع 10٪',
	'process_3_d'     => 'ادفع 10٪ للتأكيد، وادفع الرصيد المتبقي عند الاستلام',

	'routes_title'       => 'إلى أين تأخذك سياراتنا',
	'route_1'            => 'كازبيجي وجوداوري',
	'route_2'            => 'طريق النبيذ في كاخيتي',
	'route_3'            => 'سفانيتي',
	'route_4'            => 'ساحل البحر الأسود',
	'testimonials_title' => 'ماذا يقول عملاؤنا',
	'faq_title'          => 'الأسئلة الشائعة',
	'cta_title'          => 'مستعد لاستكشاف جورجيا؟',
	'cta_subtitle'       => 'اختر سيارة وتواريخك — ونحن نتولى الباقي',
	'places_title'       => 'أماكن للزيارة',
	'places_subtitle'    => 'اكتشف أجمل الوجهات في جورجيا',
	'all_regions'        => 'كل المناطق',
	'view_on_map'        => 'عرض على الخريطة',
	'place_driving_title'  => 'القيادة إلى %s',
	'place_drive_plan'     => 'خطط للرحلة',
	'place_driving_policy' => 'تحقق من الطقس والإغلاقات الرسمية وأضرار الطريق قبل المغادرة. إذن التأجير لا يتجاوز طريقًا مغلقًا أو غير آمن.',
	'place_route_guides'   => 'اقرأ أدلة القيادة',
	'place_choose_car'     => 'قارن سيارات 4x4 وAWD الفعلية',

	'footer_desc'     => 'خدمة تأجير سيارات فاخرة في جورجيا. اكتشف جمال القوقاز براحة وموثوقية.',
	'quick_links'     => 'روابط سريعة',
	'contact_info'    => 'معلومات الاتصال',
	'follow_us'       => 'تابعنا',
	'we_deliver'       => 'نوصل إلى',
	'rights'          => 'جميع الحقوق محفوظة.',

	'contact_title'    => 'مكتب تأجير سيارات في متاتسميندا، تبليسي',
	'contact_subtitle' => 'راسلنا لأي أسئلة أو عروض خاصة أو مساعدة',
	'contact_whatsapp' => 'راسلنا على واتساب',
	'contact_phone'    => 'اتصل بنا',
	'contact_email'    => 'راسلنا بالبريد',
	'contact_hours'    => 'ساعات العمل',
	'contact_address'  => 'العنوان',
	'contact_form_title'    => 'أرسل لنا رسالة',
	'contact_form_name'     => 'الاسم',
	'contact_form_email'    => 'البريد الإلكتروني',
	'contact_form_phone'    => 'الهاتف (اختياري)',
	'contact_form_message'  => 'الرسالة',
	'contact_form_send'     => 'المتابعة عبر واتساب',
	'contact_form_sent'     => 'شكرًا — تم إرسال رسالتك.',
	'contact_form_error'    => 'تعذر إرسال رسالتك. حاول مرة أخرى أو تواصل معنا عبر واتساب.',
	'contact_google_rating' => 'تقييم %s على خرائط Google',
	'contact_map_title'     => 'مكتب Geolander على خرائط Google',
	'office_location'       => 'يقع مكتبنا لتأجير سيارات 4x4 في قلب تبليسي — %1$s، %2$s.',

	// Positioning + fleet card CTA.
	'slogan'            => 'تعال من أجل الطرق. وارجع بالذكريات.',
	'price_range_label' => 'جميع السيارات',
	'ask_whatsapp'      => 'تواصل عبر واتساب',
	'check_details'      => 'التفاصيل',

	// 404 page.
	'nf_code'          => '404',
	'nf_text'          => 'الصفحة غير موجودة. العودة إلى',
	'nf_home'          => 'الصفحة الرئيسية',
	'nf_or'            => 'أو',
	'nf_fleet'         => 'تصفح أسطولنا',
];
