<?php
/** French UI strings. */

defined( 'ABSPATH' ) || exit;

return [
	'nav_home'        => 'Accueil',
	'nav_fleet'       => 'Notre flotte',
	'nav_places'      => 'À visiter',
	'nav_travel_info' => 'Infos voyage',
	'nav_music'       => 'Musique géorgienne',
	'nav_blog'        => 'Blog',
	'nav_terms'       => 'Conditions',
	'nav_contact'     => 'Contact',
	'book_now'        => 'Réserver',

	'hero_title'      => 'Explorez la Géorgie à votre façon',
	'hero_subtitle'   => 'Une flotte 4x4 premium pour les routes du Caucase — assurance complète incluse et livraison gratuite à l\'aéroport',
	'hero_cta'        => 'Voir notre flotte',
	'hero_cta2'       => 'Voir les destinations',

	'trust_cancel'    => 'Annulation gratuite',
	'trust_fees'      => 'Sans frais cachés',
	'trust_delivery'  => 'Livraison gratuite à l\'aéroport',
	'trust_support'   => 'Assistance 24h/24 sur WhatsApp',
	'trust_insurance' => 'Assurance incluse',

	'fleet_title'     => 'Notre flotte',
	'fleet_subtitle'  => 'De vraies voitures, de vraies photos — vous recevez exactement la voiture que vous réservez',
	'seats'           => 'places',
	'automatic'       => 'Automatique',
	'manual'          => 'Manuelle',
	'gasoline'        => 'Essence',
	'diesel'          => 'Diesel',
	'hybrid'          => 'Hybride',
	'electric'        => 'Électrique',
	'available'       => 'Disponible',
	'unavailable'     => 'Réservée',
	'from_per_day'    => 'dès/jour',
	'per_day'         => '/jour',
	'days'            => 'jours',
	'view_all'        => 'Tout voir',
	'view_details'    => 'Détails',
	'photos_soon'     => 'Photos à venir',

	'booking_title'      => 'Réserver cette voiture',
	'pickup_date'        => 'Date de prise en charge',
	'return_date'        => 'Date de retour',
	'total_price'        => 'Prix total',
	'price_per_day'      => 'Prix par jour',
	'total_days'         => 'Nombre de jours',
	'your_name'          => 'Votre nom',
	'book_whatsapp'      => 'Réserver via WhatsApp',
	'no_prepayment'      => 'Aucun prépaiement — payez à la prise en charge',
	'free_cancellation'  => 'Annulation gratuite jusqu\'à 24 h avant la prise en charge',
	'price_locked'       => 'Ce prix est définitif — WhatsApp ne sert qu\'à le confirmer',
	'select_dates'       => 'Choisissez vos dates',
	'quote_error'        => 'Impossible de calculer le prix — essayez d\'autres dates',
	'booking_summary'    => 'Récapitulatif de réservation',
	'send_request'       => 'Envoyer la demande sur WhatsApp',
	'whats_next_title'   => 'Et ensuite ?',
	'whats_next_text'    => 'Confirmation sous 30 minutes (09h00–22h00). Paiement à la prise en charge.',

	'pricing_title'   => 'Tarifs saisonniers (USD/jour)',
	'season'          => 'Saison',
	'days_label'      => 'jours',

	'specs_title'       => 'Caractéristiques',
	'spec_year'         => 'Année',
	'spec_seats'        => 'Places',
	'spec_transmission' => 'Boîte',
	'spec_fuel'         => 'Carburant',
	'spec_color'        => 'Couleur',
	'spec_body'         => 'Carrosserie',

	'terrain_title'   => 'Où pouvez-vous aller',
	'terrain_text'    => 'Kazbegi, Goudaouri, Kakhétie, Svanétie — toutes nos voitures sont autorisées sur les routes de montagne et les pistes. Demandez-nous aussi pour la Touchétie.',
	'included_title'  => 'Tout est inclus',
	'included_1'      => 'Assurance complète',
	'included_2'      => 'Kilométrage illimité',
	'included_3'      => 'Pneus hiver en saison',
	'included_4'      => 'Second conducteur gratuit',
	'included_5'      => 'Livraison gratuite à l\'aéroport',
	'included_6'      => 'Assistance routière 24h/24',

	'process_title'   => 'Comment ça marche',
	'process_1_t'     => 'Choisissez votre voiture et vos dates',
	'process_1_d'     => 'Votre prix exact s\'affiche instantanément — selon la saison et la durée',
	'process_2_t'     => 'Envoyez une demande via WhatsApp',
	'process_2_d'     => 'Un message prêt avec votre numéro de réservation — confirmation en 30 minutes',
	'process_3_t'     => 'Prenez la route',
	'process_3_d'     => 'Paiement à la prise en charge. Récupérez la voiture et partez à l\'aventure',

	'routes_title'       => 'Où nos voitures vous emmènent',
	'route_1'            => 'Kazbegi et Goudaouri',
	'route_2'            => 'Route des vins de Kakhétie',
	'route_3'            => 'Svanétie',
	'route_4'            => 'Côte de la mer Noire',
	'testimonials_title' => 'Ce que disent nos clients',
	'faq_title'          => 'Questions fréquentes',
	'cta_title'          => 'Prêt à explorer la Géorgie ?',
	'cta_subtitle'       => 'Choisissez une voiture et vos dates — nous nous occupons du reste',
	'places_title'       => 'À visiter',
	'places_subtitle'    => 'Découvrez les plus belles destinations de Géorgie',
	'all_regions'        => 'Toutes les régions',
	'view_on_map'        => 'Voir sur la carte',

	'footer_desc'     => 'Service premium de location de voitures en Géorgie. Découvrez la beauté du Caucase avec confort et fiabilité.',
	'quick_links'     => 'Liens rapides',
	'contact_info'    => 'Coordonnées',
	'follow_us'       => 'Suivez-nous',
	'rights'          => 'Tous droits réservés.',

	'contact_title'    => 'Contactez-nous',
	'contact_subtitle' => 'Écrivez-nous pour toute question, offre personnalisée ou assistance',
	'contact_whatsapp' => 'Écrire sur WhatsApp',
	'contact_phone'    => 'Appeler',
	'contact_email'    => 'Envoyer un e-mail',
	'contact_hours'    => 'Horaires',
	'contact_address'  => 'Adresse',

	// Positioning + fleet card CTA.
	'slogan'            => 'Venez pour les routes. Repartez avec les souvenirs.',
	'price_range_label' => 'Toutes les voitures',
	'ask_whatsapp'      => 'Écrire sur WhatsApp',

	// 404 page.
	'nf_code'          => '404',
	'nf_text'          => 'Page introuvable. Retour à',
	'nf_home'          => 'l’accueil',
	'nf_or'            => 'ou',
	'nf_fleet'         => 'découvrez notre flotte',
];
