<?php
/** English UI strings (fallback catalog / x-default). */

defined( 'ABSPATH' ) || exit;

return [
	'nav_home'        => 'Home',
	'nav_fleet'       => 'Our Fleet',
	'nav_places'      => 'Places to Visit',
	'nav_travel_info' => 'Travel Info',
	'nav_music'       => 'Georgian Music',
	'nav_blog'        => 'Blog',
	'nav_terms'       => 'Terms',
	'nav_contact'     => 'Contact',
	'book_now'        => 'Book Now',

	'hero_title'      => 'Explore Georgia Your Way',
	'hero_subtitle'   => 'Premium 4x4 car rental in Tbilisi, built for Caucasus mountain roads — full insurance included and free airport delivery',
	'hero_cta'        => 'Browse Our Fleet',
	'hero_cta2'       => 'View Destinations',

	'trust_cancel'    => 'Free cancellation',
	'trust_fees'      => 'No hidden fees',
	'trust_delivery'  => 'Free airport delivery',
	'trust_support'   => '24/7 WhatsApp support',
	'trust_insurance' => 'Insurance included',

	'fleet_title'     => 'Our Fleet',
	'fleet_subtitle'  => 'Real cars, real photos — the exact car you book is the one you get',
	'seats'           => 'seats',
	'automatic'       => 'Automatic',
	'manual'          => 'Manual',
	'gasoline'        => 'Gasoline',
	'diesel'          => 'Diesel',
	'hybrid'          => 'Hybrid',
	'electric'        => 'Electric',
	'available'       => 'Available',
	'unavailable'     => 'Booked',
	'from_per_day'    => 'from/day',
	'per_day'         => '/day',
	'days'            => 'days',
	'view_all'        => 'View all',
	'view_details'    => 'Details',
	'photos_soon'     => 'Photos coming soon',

	'booking_title'      => 'Book this car',
	'pickup_date'        => 'Pickup date',
	'return_date'        => 'Return date',
	'total_price'        => 'Total price',
	'price_per_day'      => 'Price per day',
	'total_days'         => 'Total days',
	'your_name'          => 'Your name',
	'book_whatsapp'      => 'Book via WhatsApp',
	'no_prepayment'      => 'No prepayment needed — pay at pickup',
	'free_cancellation'  => 'Free cancellation up to 24h before pickup',
	'price_locked'       => 'This price is final — WhatsApp only confirms it',
	'select_dates'       => 'Select dates',
	'quote_error'        => 'Could not price these dates — try different ones',
	'booking_summary'    => 'Booking summary',
	'send_request'       => 'Send request on WhatsApp',
	'whats_next_title'   => 'What happens next?',
	'whats_next_text'    => 'We confirm within 30 minutes (09:00–22:00). Payment at pickup.',

	'pricing_title'   => 'Seasonal pricing (USD/day)',
	'season'          => 'Season',
	'days_label'      => 'days',

	'specs_title'       => 'Specifications',
	'spec_year'         => 'Year',
	'spec_seats'        => 'Seats',
	'spec_transmission' => 'Transmission',
	'spec_fuel'         => 'Fuel',
	'spec_color'        => 'Color',
	'spec_body'         => 'Body type',

	'terrain_title'   => 'Where you can go',
	'terrain_text'    => 'Kazbegi, Gudauri, Kakheti, Svaneti — all our cars are permitted on mountain and gravel roads. Ask us about Tusheti too.',
	'included_title'  => 'Everything included',
	'included_1'      => 'Full insurance',
	'included_2'      => 'Unlimited mileage',
	'included_3'      => 'Winter tires in season',
	'included_4'      => 'Free second driver',
	'included_5'      => 'Free airport delivery',
	'included_6'      => '24/7 roadside assistance',

	'process_title'   => 'How it works',
	'process_1_t'     => 'Choose your car and dates',
	'process_1_d'     => 'Your exact price appears instantly — by season and rental length',
	'process_2_t'     => 'Send a request via WhatsApp',
	'process_2_d'     => 'A ready message with your booking number — we confirm within 30 minutes',
	'process_3_t'     => 'Hit the road',
	'process_3_d'     => 'Pay at pickup. Take the car and start your adventure',

	'routes_title'       => 'Where our cars take you',
	'route_1'            => 'Kazbegi & Gudauri',
	'route_2'            => 'Kakheti Wine Route',
	'route_3'            => 'Svaneti',
	'route_4'            => 'Black Sea Coast',
	'testimonials_title' => 'What our customers say',
	'faq_title'          => 'Frequently asked questions',
	'cta_title'          => 'Ready to explore Georgia?',
	'cta_subtitle'       => 'Pick a car, pick your dates — we handle the rest',
	'places_title'       => 'Places to Visit',
	'places_subtitle'    => 'Discover the most beautiful destinations in Georgia',
	'all_regions'        => 'All regions',
	'view_on_map'        => 'View on map',

	'footer_desc'     => 'Premium car rental service in Georgia. Explore the beauty of the Caucasus with comfort and reliability.',
	'quick_links'     => 'Quick links',
	'contact_info'    => 'Contact info',
	'follow_us'       => 'Follow us',
	'we_deliver'       => 'We deliver to',
	'rights'          => 'All rights reserved.',

	'contact_title'    => 'Contact us',
	'contact_subtitle' => 'Write to us with questions, custom offers, or for any help',
	'contact_whatsapp' => 'Message us on WhatsApp',
	'contact_phone'    => 'Call us',
	'contact_email'    => 'Email us',
	'contact_hours'    => 'Business hours',
	'contact_address'  => 'Address',

	// Positioning + fleet card CTA.
	'slogan'            => 'Come for the roads. Leave with the memories.',
	'price_range_label' => 'All cars',
	'ask_whatsapp'      => 'Ask on WhatsApp',
	'check_details'      => 'Check details',

	// 404 page.
	'nf_code'          => '404',
	'nf_text'          => 'Page not found. Go back',
	'nf_home'          => 'home',
	'nf_or'            => 'or',
	'nf_fleet'         => 'browse our fleet',
];
