<?php
/** Arabic UI strings (RTL). */

defined( 'ABSPATH' ) || exit;

return [
	'from' => 'من',
	'nav_locations' => 'المدن',
	'nav_where_drive' => 'أين يمكنك القيادة',
	'nav_guides' => 'أدلة',
	'nav_trust' => 'الثقة والشروط',
	'breadcrumb' => 'مسار التنقل',
	'price_on_request' => 'السعر عند الطلب',
	'nav_home'        => 'الرئيسية',
	'nav_fleet'       => 'أسطولنا',
	'nav_places'      => 'أماكن للزيارة',
	'nav_travel_info' => 'معلومات السفر',
	'nav_music'       => 'الموسيقى الجورجية',
	'nav_blog'        => 'المدونة',
	'nav_terms'       => 'الشروط',
	'nav_contact'     => 'اتصل بنا',
	'nav_about'       => 'حول Geolander',
	'book_now'        => 'احجز الآن',

	'hero_title'      => 'تأجير سيارات دفع رباعي 4×4 في تبليسي، جورجيا — السيارة التي تحجزها هي بالضبط التي تستلمها',
	'hero_subtitle'   => 'أسطول دفع رباعي فاخر لطرق جبال القوقاز — تأمين شامل وتوصيل مجاني إلى مطار تبليسي',
	'hero_cta'        => 'تصفح أسطولنا',
	'hero_cta2'       => 'عرض الوجهات',

	'trust_cancel'    => 'شروط إلغاء واضحة',
	'trust_fees'      => 'بدون رسوم خفية',
	'trust_delivery'  => 'توصيل مجاني إلى مطار تبليسي',
	'trust_support'   => 'دعم واتساب على مدار الساعة',
	'trust_insurance' => 'التأمين مشمول',

	'fleet_title'     => 'أسطولنا',
	'fleet_subtitle'  => 'سيارات حقيقية وصور حقيقية — السيارة التي تحجزها هي التي تستلمها',
	'seats'           => 'مقاعد',
	'automatic'       => 'أوتوماتيك',
	'manual'          => 'يدوي',
	'gasoline'        => 'بنزين',
	'diesel'          => 'ديزل',
	'hybrid'          => 'هجين',
	'electric'        => 'كهربائي',
	'available'       => 'متاحة',
	'unavailable'     => 'محجوزة',
	'from_per_day'    => 'من/يوم',
	'per_day'         => '/يوم',
	'days'            => 'أيام',
	'view_all'        => 'عرض الكل',
	'view_details'    => 'التفاصيل',
	'photos_soon'     => 'الصور قريباً',

	'booking_title'      => 'احجز هذه السيارة',
	'pickup_date'        => 'تاريخ الاستلام',
	'return_date'        => 'تاريخ الإرجاع',
	'total_price'        => 'السعر الإجمالي',
	'price_per_day'      => 'السعر لليوم',
	'total_days'         => 'إجمالي الأيام',
	'your_name'          => 'اسمك',
	'book_whatsapp'      => 'احجز عبر واتساب',
	'booking_prepayment'  => 'دفعة مسبقة 10٪ تؤكد الحجز',
	'cancellation_refund' => 'يُسترد 50٪ من الدفعة المسبقة عند الإلغاء قبل الاستلام بـ30 يومًا أو أكثر',
	'price_locked'       => 'يشمل الإجمالي الإيجار ورسوم الاستلام والإرجاع المختارة؛ نؤكد التوفر عبر واتساب',
	'select_dates'       => 'اختر التواريخ',
	'quote_error'        => 'تعذر حساب السعر — جرّب تواريخ أخرى',
	'booking_summary'    => 'ملخص الحجز',
	'send_request'       => 'أرسل الطلب عبر واتساب',
	'whats_next_title'   => 'ماذا بعد؟',
	'whats_next_text'    => 'نؤكد خلال 30 دقيقة (09:00–22:00). يتطلب تأكيد الحجز دفعة مسبقة بنسبة 10٪.',

	'pricing_title'   => 'الأسعار الموسمية (دولار/يوم)',
	'season'          => 'الموسم',
	'days_label'      => 'أيام',

	'specs_title'       => 'المواصفات',
	'spec_year'         => 'السنة',
	'spec_seats'        => 'المقاعد',
	'spec_transmission' => 'ناقل الحركة',
	'spec_fuel'         => 'الوقود',
	'spec_color'        => 'اللون',
	'spec_body'         => 'نوع الهيكل',

	'terrain_title'   => 'إلى أين يمكنك الذهاب',
	'terrain_text'    => 'كازبيجي، جوداوري، كاخيتي، سفانيتي — جميع سياراتنا مسموح لها بالطرق الجبلية وغير المعبدة. اسألنا عن توشيتي أيضاً.',
	'included_title'  => 'مشمول مع كل عملية تأجير',
	'included_1'      => 'تأمين شامل',
	'included_2'      => 'كيلومترات غير محدودة',
	'included_3'      => 'إطارات شتوية في موسمها',
	'included_4'      => 'بدون وديعة تأمين',
	'included_5'      => 'توصيل مجاني إلى مطار تبليسي',
	'included_6'      => 'دعم عبر واتساب على مدار الساعة',

	'process_title'   => 'كيف يعمل',
	'process_1_t'     => 'اختر سيارتك وتواريخك',
	'process_1_d'     => 'يظهر سعرك الدقيق فوراً — حسب الموسم ومدة الإيجار',
	'process_2_t'     => 'أرسل طلباً عبر واتساب',
	'process_2_d'     => 'رسالة جاهزة برقم حجزك — نؤكد خلال 30 دقيقة',
	'process_3_t'     => 'أكد الحجز بدفع 10٪',
	'process_3_d'     => 'ادفع 10٪ للتأكيد، وادفع الرصيد المتبقي عند الاستلام',

	'routes_title'       => 'إلى أين تأخذك سياراتنا',
	'route_1'            => 'كازبيجي وجوداوري',
	'route_2'            => 'طريق النبيذ في كاخيتي',
	'route_3'            => 'سفانيتي',
	'route_4'            => 'ساحل البحر الأسود',
	'testimonials_title' => 'تقييمات العملاء على خرائط Google',
	'faq_title'          => 'الأسئلة الشائعة',
	'cta_title'          => 'مستعد لاستكشاف جورجيا؟',
	'cta_subtitle'       => 'اختر سيارة وتواريخك — ونحن نتولى الباقي',
	'places_title'       => 'أماكن للزيارة',
	'places_subtitle'    => 'اكتشف أجمل الوجهات في جورجيا',
	'all_regions'        => 'كل المناطق',
	'view_on_map'        => 'عرض على الخريطة',
	'place_driving_title'  => 'القيادة إلى %s',
	'place_drive_plan'     => 'خطط للرحلة',
	'place_driving_policy' => 'تحقق من الطقس والإغلاقات الرسمية وأضرار الطريق قبل المغادرة. إذن التأجير لا يتجاوز طريقًا مغلقًا أو غير آمن.',
	'place_route_guides'   => 'اقرأ أدلة القيادة',
	'place_choose_car'     => 'قارن سيارات 4x4 وAWD الفعلية',

	'footer_desc'     => 'خدمة تأجير سيارات فاخرة في جورجيا. اكتشف جمال القوقاز براحة وموثوقية.',
	'quick_links'     => 'روابط سريعة',
	'contact_info'    => 'معلومات الاتصال',
	'follow_us'       => 'تابعنا',
	'we_deliver'       => 'نوصل إلى',
	'rights'          => 'جميع الحقوق محفوظة.',

	'contact_title'    => 'مكتب تأجير سيارات في متاتسميندا، تبليسي',
	'contact_subtitle' => 'راسلنا لأي أسئلة أو عروض خاصة أو مساعدة',
	'contact_whatsapp' => 'راسلنا على واتساب',
	'contact_phone'    => 'اتصل بنا',
	'contact_email'    => 'راسلنا بالبريد',
	'contact_hours'    => 'ساعات العمل',
	'contact_address'  => 'العنوان',
	'contact_form_title'    => 'أرسل لنا رسالة',
	'contact_form_name'     => 'الاسم',
	'contact_form_email'    => 'البريد الإلكتروني',
	'contact_form_phone'    => 'الهاتف (اختياري)',
	'contact_form_message'  => 'الرسالة',
	'contact_form_send'     => 'المتابعة عبر واتساب',
	'contact_form_sent'     => 'شكرًا — تم إرسال رسالتك.',
	'contact_form_error'    => 'تعذر إرسال رسالتك. حاول مرة أخرى أو تواصل معنا عبر واتساب.',
	'contact_google_rating' => 'تقييم %s على خرائط Google',
	'contact_map_title'     => 'مكتب Geolander على خرائط Google',
	'office_location'       => 'يقع مكتبنا لتأجير سيارات 4x4 في قلب تبليسي — %1$s، %2$s.',

	// Positioning + fleet card CTA.
	'slogan'            => 'تعال من أجل الطرق. وارجع بالذكريات.',
	'price_range_label' => 'جميع السيارات',
	'price_range_sentence' => 'من %1$s إلى %2$s يومياً',
	'ask_whatsapp'      => 'تواصل عبر واتساب',
	'check_details'      => 'التفاصيل',

	// 404 page.
	'nf_code'          => '404',
	'nf_text'          => 'الصفحة غير موجودة. العودة إلى',
	'nf_home'          => 'الصفحة الرئيسية',
	'nf_or'            => 'أو',
	'nf_fleet'         => 'تصفح أسطولنا',
	'nf_agent_recovery'=> 'روابط استعادة الوكيل',

	// Added 2026-09-07 — key parity with strings-en.php
	'your_email'         => 'بريدك الإلكتروني',
	'pickup_location'    => 'مكان الاستلام',
	'return_location'    => 'مكان التسليم',
	'free'               => 'مجاناً',
	'location_tbilisi_office'  => 'مكتب تبليسي · متاتسميندا',
	'location_tbilisi_airport' => 'مطار تبليسي (TBS)',
	'location_kutaisi_airport' => 'مطار كوتايسي (KUT)',
	'location_batumi_airport'  => 'مطار باتومي (BUS)',
	'rental_price'       => 'إيجار السيارة',
	'pickup_charge'      => 'رسوم الاستلام',
	'return_charge'      => 'رسوم التسليم',
	'final_total'        => 'الإجمالي النهائي',
	'prepayment_amount'  => 'دفعة مقدمة 10% لتأكيد الحجز',
	'balance_at_pickup'  => 'المبلغ المتبقي عند الاستلام',
	'customer_details_error' => 'أدخل اسمك وعنوان بريد إلكتروني صالح.',
	'receipt_sent'       => 'أرسلنا ملخص طلبك إلى بريدك الإلكتروني. تابع عبر واتساب ليؤكد فريقنا توفر السيارة والدفعة المقدمة 10%.',
	'receipt_not_sent'   => 'تم حفظ طلبك. تابع عبر واتساب؛ يمكن لفريقنا استخدام رقم حجزك وإرسال التأكيد يدوياً.',
	'spec_drivetrain'    => 'نظام الدفع',
	'spec_fuel_economy'  => 'استهلاك الوقود',
	'rental_facts_title'              => 'شروط إيجار واضحة لهذه السيارة بالتحديد',
	'rental_exact_car'                => 'ضمان السيارة',
	'rental_exact_car_value'          => 'السيارة نفسها المعروضة والمحجوزة — وليست «أو ما شابهها» أبداً',
	'rental_winter'                   => 'إطارات شتوية',
	'rental_winter_value'             => 'تُركَّب في الشتاء ومشمولة مجاناً',
	'rental_insurance'                => 'التأمين مشمول',
	'rental_insurance_value'          => 'تأمين شامل، بما في ذلك الحوادث الفردية دون طرف آخر',
	'rental_excess'                   => 'مبلغ التحمّل',
	'rental_excess_value'             => 'لا يوجد',
	'rental_coverage'                 => 'الجنوط والزجاج الأمامي',
	'rental_coverage_value'           => 'مشمولة بالتأمين',
	'rental_not_covered'              => 'غير مشمول',
	'rental_not_covered_value'        => 'الإطارات',
	'rental_liability'                => 'المسؤولية تجاه الغير',
	'rental_liability_value'          => 'مغطاة حتى 30,000 GEL',
	'rental_deposit'                  => 'وديعة التأمين',
	'rental_deposit_value'            => 'لا توجد — لا نقداً ولا خصماً من البطاقة ولا حجزاً مسبقاً للمبلغ',
	'rental_mileage'                  => 'المسافة المقطوعة',
	'rental_mileage_value'            => 'غير محدودة داخل جورجيا',
	'rental_delivery'                 => 'الاستلام / التسليم في المطار',
	'rental_delivery_value'           => 'تبليسي مجاناً. كوتايسي %1$s للاتجاه الواحد؛ باتومي %2$s للاتجاه الواحد.',
	'rental_insurance_exclusions'     => 'يسقط التأمين عند القيادة في المسار المخالف، أو تجاوز الإشارة الحمراء، أو تجاوز السرعة، أو عدم إبلاغ Geolander بموقع الحادث.',
	'city_seo_title'       => 'تأجير سيارات في %s، جورجيا (الدولة) — بدون وديعة، تأمين شامل',
	'city_seo_description' => 'استأجر سيارة 4x4 أو AWD محددة مع التوصيل في %s، جورجيا. بدون وديعة تأمين، تأمين شامل، صور حقيقية للسيارة التي ستستلمها، ودعم 24/7 على واتساب.',
	'longterm_table_title' => 'أسعار الإيجار طويل الأمد حسب مدة الإيجار (دولار في اليوم)',
	'longterm_vehicle'     => 'السيارة',
	'longterm_season'      => 'الموسم',
	'longterm_tier_short'  => '1–2 يوم',
	'longterm_tier_19_30'  => '19–30 يوماً',
	'longterm_tier_31'     => '31+ يوماً',
	'longterm_saving'      => 'التوفير عند 31+ يوماً مقارنةً بالإيجار القصير',
	'longterm_note'        => 'تُقرأ الأسعار مباشرةً من جدول الأسعار الموسمي لكل سيارة. وإذا امتد الإيجار على موسمين، يُحتسب السعر يوماً بيوم حسب سعر كل موسم.',
	'longterm_cta'         => 'اطلب عرض سعر شهري عبر واتساب',
	'longterm_unpriced'    => 'السعر عند الطلب',
	'nav_long_term'        => 'الإيجار طويل الأمد',
	'home_seo_title'       => 'تأجير سيارات 4x4 في جورجيا (الدولة) — تبليسي',
];
